Repository controlplaneio-fluxcd/flux-operator, pull requests merged in 2024-06, with the labels that each got.

#15 Takeover a bootstrapped cluster
  Makefile
  README.md
  cmd/main.go
  config/manager/deployment.yaml
  internal/builder/build.go
  internal/builder/build_test.go
  internal/builder/templates.go
  internal/builder/testdata/v2.3.0-golden/default.kustomization.yaml
  internal/builder/testdata/v2.3.0-golden/patches.kustomization.yaml
  internal/builder/testdata/v2.3.0-golden/profiles.kustomization.yaml
  internal/builder/testdata/v2.3.0-golden/storage.kustomization.yaml
Labels: enhancement

#16 Add support for disabling the reconciliation
  api/v1/fluxinstance_types.go
  internal/controller/fluxinstance_controller.go
  internal/controller/fluxinstance_controller_test.go
  internal/controller/fluxinstance_uninstaller.go
Labels: enhancement

#17 Add API docs for the FluxInstance custom resource
  README.md
  docs/api/v1/fluxinstance.md
Labels: documentation

#18 Publish distro manifests at release time
  .github/workflows/release.yml
  Makefile
  config/manager/kustomization.yaml
Labels: enhancement

#21 fix API docs typo
  docs/api/v1/fluxinstance.md
Labels: documentation

#19 Add OperatorHub manifests
  .github/workflows/e2e-olm.yml
  Makefile
  config/operatorhub/flux-operator/Dockerfile.opm
  config/operatorhub/flux-operator/bundle.Dockerfile
  config/operatorhub/flux-operator/ci.yaml
  config/operatorhub/flux-operator/flux-operator.package.yaml
  config/operatorhub/flux-operator/scripts/opm-index.sh
  config/operatorhub/flux-operator/testdata/001-flux-system-ns.yaml
  config/operatorhub/flux-operator/testdata/002-flux-system-og.yaml
  config/operatorhub/flux-operator/testdata/003-catalog-source.yaml
  config/operatorhub/flux-operator/testdata/004-operator-subscription.yaml
  config/operatorhub/flux-operator/testdata/kustomization.yaml
  config/operatorhub/flux-operator/v0.3.0/manifests/flux-operator.clusterserviceversion.yaml
  config/operatorhub/flux-operator/v0.3.0/manifests/fluxinstances.fluxcd.controlplane.io.crd.yaml
  config/operatorhub/flux-operator/v0.3.0/metadata/annotations.yaml
  config/operatorhub/flux-operator/v0.3.0/tests/scorecard/config.yaml
  test/e2e/e2e_test.go
  test/e2e/instance_test.go
  test/e2e/utils.go
  test/olm/e2e_suite_test.go
  test/olm/e2e_test.go
  test/olm/instance_test.go
  test/olm/scorecard_test.go
Labels: enhancement

#32 Include distro digests in manifests artifact
  .github/workflows/push-manifests.yml
  .github/workflows/release.yml
  .gitignore
  Makefile
  hack/build-dist-manifests.sh
Labels: area/ci

#33 Implement automatic distribution updates from OCI artifacts
  README.md
  api/v1/fluxinstance_types.go
  config/crd/bases/fluxcd.controlplane.io_fluxinstances.yaml
  config/data/flux-images/VERSION
  config/data/flux-images/v2.2.0/enterprise-alpine.yaml
  config/data/flux-images/v2.2.0/enterprise-distroless.yaml
  config/data/flux-images/v2.2.0/upstream-alpine.yaml
  config/data/flux-images/v2.2.1/enterprise-alpine.yaml
  config/data/flux-images/v2.2.1/enterprise-distroless.yaml
  config/data/flux-images/v2.2.1/upstream-alpine.yaml
  config/data/flux-images/v2.2.2/enterprise-alpine.yaml
  config/data/flux-images/v2.2.2/enterprise-distroless.yaml
  config/data/flux-images/v2.2.2/upstream-alpine.yaml
  config/data/flux-images/v2.2.3/enterprise-alpine.yaml
  config/data/flux-images/v2.2.3/enterprise-distroless.yaml
  config/data/flux-images/v2.2.3/upstream-alpine.yaml
  config/data/flux-images/v2.3.0/enterprise-alpine.yaml
  config/data/flux-images/v2.3.0/enterprise-distroless.yaml
  config/data/flux-images/v2.3.0/upstream-alpine.yaml
  config/samples/fluxcd_v1_fluxinstance.yaml
  docs/api/v1/fluxinstance.md
  go.mod
  go.sum
  hack/vendor-flux-manifests.sh
  internal/builder/images.go
  internal/builder/images_test.go
  internal/builder/pull.go
  internal/builder/testdata/flux-images/v2.3.0/enterprise-alpine.yaml
  internal/builder/testdata/flux-images/v2.3.0/enterprise-distroless.yaml
  internal/builder/testdata/flux-images/v2.3.0/upstream-alpine.yaml
  internal/controller/fluxinstance_controller.go
  internal/controller/fluxinstance_controller_test.go
Labels: enhancement, area/update-automation

#36 Generate OLM manifests and refactor e2e test suite
  .github/workflows/e2e-olm.yml
  Makefile
  config/olm/bundle/manifests/flux-operator.clusterserviceversion.yaml
  config/olm/bundle/manifests/fluxinstances.fluxcd.controlplane.io.crd.yaml
  config/olm/bundle/metadata/annotations.yaml
  config/olm/bundle/tests/scorecard/config.yaml
  config/olm/ci.yaml
  config/olm/test/bundle.Dockerfile
  config/olm/test/olm.yaml
  config/olm/test/opm.Dockerfile
  config/operatorhub/flux-operator/flux-operator.package.yaml
  config/operatorhub/flux-operator/scripts/opm-index.sh
  config/operatorhub/flux-operator/testdata/001-flux-system-ns.yaml
  config/operatorhub/flux-operator/testdata/002-flux-system-og.yaml
  config/operatorhub/flux-operator/testdata/003-catalog-source.yaml
  config/operatorhub/flux-operator/testdata/004-operator-subscription.yaml
  config/operatorhub/flux-operator/testdata/kustomization.yaml
  config/operatorhub/flux-operator/v0.3.0/manifests/fluxinstances.fluxcd.controlplane.io.crd.yaml
  config/operatorhub/flux-operator/v0.4.0/manifests/flux-operator.clusterserviceversion.yaml
  config/operatorhub/flux-operator/v0.4.0/manifests/fluxinstances.fluxcd.controlplane.io.crd.yaml
  config/operatorhub/flux-operator/v0.4.0/metadata/annotations.yaml
  config/operatorhub/flux-operator/v0.4.0/tests/scorecard/config.yaml
  docs/release/README.md
  hack/build-olm-images.sh
  hack/build-olm-manifests.sh
  test/olm/e2e_test.go
  test/olm/scorecard_test.go
Labels: area/testing, area/ci

#39 Add publishing procedure for manifests
  .github/workflows/push-manifests.yml
  docs/dev/README.md
Labels: documentation, area/update-automation

#42 Implement entitlement verification and AWS metering
  cmd/main.go
  go.mod
  go.sum
  internal/controller/entitlement_controller.go
  internal/controller/entitlement_controller_test.go
  internal/controller/fluxinstance_controller.go
  internal/entitlement/aws.go
  internal/entitlement/client.go
  internal/entitlement/default.go
Labels: area/marketplace

#46 Implement reporting for Flux installation status and statistics
  PROJECT
  README.md
  api/v1/fluxinstance_types.go
  api/v1/fluxreport_types.go
  api/v1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/fluxcd.controlplane.io_fluxreports.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/olm/bundle/manifests/flux-operator.clusterserviceversion.yaml
  config/olm/bundle/manifests/fluxreports.fluxcd.controlplane.io.crd.yaml
  config/rbac/fluxreport_editor_role.yaml
  config/rbac/fluxreport_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  config/samples/fluxcd_v1_fluxreport.yaml
  config/samples/kustomization.yaml
  docs/api/v1/fluxreport.md
  go.mod
  hack/build-olm-manifests.sh
  internal/controller/entitlement_controller.go
  internal/controller/fluxinstance_controller.go
  internal/controller/fluxreport_controller.go
  internal/controller/fluxreport_controller_test.go
  internal/controller/suite_test.go
  internal/reporter/components.go
  internal/reporter/crds.go
  internal/reporter/distribution.go
  internal/reporter/reconcilers.go
  internal/reporter/reporter.go
  internal/reporter/sync.go
Labels: enhancement, area/api

#52 Fix default values for cluster settings
  api/v1/fluxinstance_types.go
  internal/controller/fluxinstance_controller_test.go
Labels: area/api

#54 Implement Prometheus instrumentation for Flux resources
  api/v1/fluxreport_types.go
  cmd/main.go
  config/manager/deployment.yaml
  config/olm/bundle/manifests/flux-operator.clusterserviceversion.yaml
  docs/api/v1/fluxinstance.md
  docs/api/v1/fluxreport.md
  go.mod
  internal/controller/fluxinstance_controller.go
  internal/controller/suite_test.go
  internal/reporter/metrics.go
  internal/reporter/metrics_test.go
  internal/reporter/reconcilers.go
Labels: area/observability
