Repository controlplaneio-fluxcd/flux-operator, pull requests merged in 2024-12, with the labels that each got.

#120 Update dependencies to Kubernetes 1.32.0
  go.mod
  go.sum
Labels: dependencies

#123 Allow setting the sync name of a `FluxInstance`
  api/v1/fluxinstance_types.go
  config/crd/bases/fluxcd.controlplane.io_fluxinstances.yaml
  docs/api/v1/fluxinstance.md
  internal/builder/build_test.go
  internal/builder/options.go
  internal/builder/templates.go
  internal/controller/fluxinstance_controller.go
  internal/controller/fluxreport_controller_test.go
  internal/reporter/sync.go
Labels: area/api

#127 Add FluxInstance artifact reconciler
  README.md
  api/v1/fluxinstance_types.go
  cmd/main.go
  docs/api/v1/fluxinstance.md
  internal/builder/digest.go
  internal/controller/fluxinstance_artifact_controller.go
  internal/controller/fluxinstance_artifact_controller_test.go
  internal/controller/fluxinstance_artifact_manager.go
  internal/controller/fluxinstance_artifact_manager_test.go
  internal/controller/suite_test.go
Labels: area/update-automation

#128 [hotfix] Update `golang.org/x/net` to patch CVE-2024-45338
  go.mod
  go.sum
Labels: dependencies, area/cves

#130 Add the release procedure for RedHat OpenShift to docs
  docs/dev/README.md
Labels: documentation
