Repository controlplaneio-fluxcd/flux-operator, pull requests merged in 2025-02, with the labels that each got.

#160 Adhere to namespace/name standard in error/log messages in ResourceSet
  internal/controller/resourceset_controller.go
Labels: area/resourceset

#154 Introduce Flux Operator CLI
  .github/workflows/release.yml
  .goreleaser.yml
  Dockerfile
  Makefile
  cmd/cli/build.go
  cmd/cli/build_resourceset.go
  cmd/cli/client.go
  cmd/cli/completion.go
  cmd/cli/completion_bash.go
  cmd/cli/completion_fish.go
  cmd/cli/completion_powershell.go
  cmd/cli/completion_zsh.go
  cmd/cli/get.go
  cmd/cli/get_resourceset.go
  cmd/cli/main.go
  cmd/cli/reconcile.go
  cmd/cli/reconcile_resourceset.go
  cmd/cli/resume.go
  cmd/cli/resume_resourceset.go
  cmd/cli/suspend.go
  cmd/cli/suspend_resourceset.go
  cmd/operator/main.go
  go.mod
  go.sum
Labels: area/resourceset, area/cli

#171 Enable multitenancy lockdown for the ResourceSet APIs on OpenShift
  config/olm/bundle/manifests/flux-operator.clusterserviceversion.yaml
Labels: area/marketplace

#169 Build with Go 1.24 and FIPS 140-3 mode enabled
  .github/workflows/e2e-olm.yml
  .github/workflows/e2e.yaml
  .golangci.yml
  Dockerfile
  Makefile
  cmd/operator/main.go
  go.mod
Labels: dependencies, area/ci

#173 Add GitHub App authentication for ResourceSetInputProvider API
  docs/api/v1/resourcesetinputprovider.md
  go.mod
  go.sum
  internal/controller/resourcesetinputprovider_controller.go
Labels: enhancement, area/resourceset

#175 Enable leader election by default
  cmd/operator/main.go
  config/olm/bundle/manifests/flux-operator.clusterserviceversion.yaml
Labels: area/lifecycle

#176 Add Flux v2.5.0 distribution
  config/data/flux-images/VERSION
  config/data/flux-images/v2.4.0/enterprise-alpine.yaml
  config/data/flux-images/v2.5.0/enterprise-alpine.yaml
  config/data/flux-images/v2.5.0/enterprise-distroless.yaml
  config/data/flux-images/v2.5.0/upstream-alpine.yaml
  config/data/flux/v2.5.0/helm-controller.yaml
  config/data/flux/v2.5.0/image-automation-controller.yaml
  config/data/flux/v2.5.0/image-reflector-controller.yaml
  config/data/flux/v2.5.0/kustomize-controller.yaml
  config/data/flux/v2.5.0/notification-controller.yaml
  config/data/flux/v2.5.0/policies.yaml
  config/data/flux/v2.5.0/rbac.yaml
  config/data/flux/v2.5.0/source-controller.yaml
Labels: area/update-automation

#177 Add ResourceSet guides to readme
  README.md
Labels: documentation

#187 Report `ResourceSetInputProvider` errors in status and events
  internal/controller/resourcesetinputprovider_controller.go
  internal/controller/resourcesetinputprovider_controller_test.go
Labels: area/resourceset

#188 Introduce `DEFAULT_SERVICE_ACCOUNT` env var for OLM config
  cmd/operator/main.go
  docs/api/v1/resourceset.md
Labels: area/marketplace

#189 Add `.spec.sync.provider` field to FluxInstance API
  api/v1/fluxinstance_types.go
  config/crd/bases/fluxcd.controlplane.io_fluxinstances.yaml
  docs/api/v1/fluxinstance.md
  internal/builder/build_test.go
  internal/builder/options.go
  internal/builder/templates.go
  internal/controller/fluxinstance_controller.go
  internal/controller/fluxinstance_controller_test.go
Labels: area/api

#190 Publish OpenAPI JSON schemas for CRDs
  .github/workflows/release.yml
  .goreleaser.yml
Labels: area/ci

#192 Update `fluxcd/pkg/runtime` to v0.54.0
  cmd/operator/main.go
  go.mod
  go.sum
  internal/controller/fluxinstance_controller.go
  internal/controller/fluxinstance_controller_test.go
  internal/controller/fluxreport_controller_test.go
  internal/controller/resourceset_controller.go
  internal/controller/resourceset_controller_test.go
  internal/controller/resourcesetinputprovider_controller_test.go
  internal/controller/suite_test.go
Labels: dependencies

#194 Fix release workflow CRD JSON schema gen
  .github/workflows/release.yml
Labels: area/ci

#198 Add standalone Service definition to OLM bundle
  config/olm/bundle/manifests/flux-operator.clusterserviceversion.yaml
  config/olm/bundle/manifests/flux-operator.service.yaml
  hack/build-olm-manifests.sh
Labels: area/marketplace

#196 Generate ConfigMaps/Secrets with data copied from existing objects
  api/v1/common_types.go
  docs/api/v1/resourceset.md
  internal/controller/resourceset_controller.go
  internal/controller/resourceset_controller_test.go
Labels: area/resourceset

#199 Export Prometheus metrics for ResourceSet APIs
  docs/api/v1/resourceset.md
  docs/api/v1/resourcesetinputprovider.md
  internal/controller/resourceset_controller.go
  internal/controller/resourcesetinputprovider_controller.go
  internal/reporter/metrics.go
  internal/reporter/metrics_test.go
Labels: area/observability, area/resourceset
