Repository controlplaneio-fluxcd/flux-operator, pull requests merged in 2025-01, with the labels that each got.

#131 Enable alerting for `FluxInstance` events
  go.mod
  go.sum
  internal/builder/build.go
  internal/builder/images.go
  internal/builder/profiles.go
  internal/builder/templates.go
  internal/controller/fluxinstance_artifact_controller_test.go
  internal/controller/fluxinstance_controller.go
  internal/controller/fluxinstance_controller_test.go
  internal/controller/fluxreport_controller_test.go
Labels: area/observability

#134 Update dependencies
  go.mod
  go.sum
Labels: dependencies

#136 docs: Fix monitoring link
  README.md
Labels: documentation

#147 Update cluster type documentation to reflect schema validation
  docs/api/v1/fluxinstance.md
Labels: documentation

#145 FluxInstance: Add `artifactPullSecret` to `spec.distribution`
  api/v1/fluxinstance_types.go
  config/crd/bases/fluxcd.controlplane.io_fluxinstances.yaml
  docs/api/v1/fluxinstance.md
  go.mod
  go.sum
  internal/builder/digest.go
  internal/builder/pull.go
  internal/controller/fluxinstance_artifact_controller.go
  internal/controller/fluxinstance_artifact_controller_test.go
  internal/controller/fluxinstance_controller.go
Labels: area/api, area/update-automation

#152 Implement `GitHubBranch` and `GitLabBranch` input providers
  api/v1/resourcesetinputprovider_types.go
  config/crd/bases/fluxcd.controlplane.io_resourcesetinputproviders.yaml
  docs/api/v1/resourcesetinputprovider.md
  internal/controller/resourcesetinputprovider_controller.go
  internal/controller/resourcesetinputprovider_controller_test.go
Labels: enhancement, area/api, area/resourceset

#159 Use `fluxcd/pkg/runtime/cel` for ResourceSet dependencies ready expression evaluation
  go.mod
  go.sum
  internal/controller/resourceset_controller.go
  internal/controller/resourceset_controller_test.go
Labels: area/resourceset
