Repository controlplaneio-fluxcd/flux-operator, pull requests merged in 2025-07, with the labels that each got.

#332 Use the secrets helper functions from `github.com/fluxcd/pkg/runtime`
  go.mod
  go.sum
  internal/controller/resourcesetinputprovider_controller.go
Labels: area/resourceset

#341 Update dependencies to Kubernetes 1.33.2
  go.mod
  go.sum
  internal/controller/fluxinstance_controller.go
  internal/controller/resourcesetinputprovider_controller.go
  internal/controller/resourcesetinputprovider_controller_oci_test.go
Labels: dependencies

#345 cli: Add `flux-operator create secret` commands
  cmd/cli/README.md
  cmd/cli/create.go
  cmd/cli/create_secret.go
  cmd/cli/create_secret_basicauth.go
  cmd/cli/create_secret_githubapp.go
  cmd/cli/create_secret_proxy.go
  cmd/cli/create_secret_registry.go
  cmd/cli/create_secret_sops.go
  cmd/cli/create_secret_ssh.go
  cmd/cli/create_secret_tls.go
  go.mod
  go.sum
Labels: enhancement, area/cli

#346 Fix broken link in secret-less auth docs
  .github/workflows/e2e.yaml
  Makefile
  docs/api/v1/resourcesetinputprovider.md
Labels: documentation

#356 cli: Add `flux-operator trace` command
  cmd/cli/README.md
  cmd/cli/client.go
  cmd/cli/trace.go
  cmd/cli/trace_test.go
  cmd/cli/trace_types.go
Labels: enhancement, area/cli

#357 cli: Add `flux-operator tree` commands
  cmd/cli/README.md
  cmd/cli/tree.go
  cmd/cli/tree_kustomization.go
  cmd/cli/tree_resourceset.go
  cmd/cli/tree_resourceset_test.go
  internal/inventory/inventory.go
  internal/inventory/reader.go
  internal/inventory/reader_test.go
Labels: enhancement, area/cli

#362 cli: Distribute the CLI as a container image
  .github/workflows/push-images.yml
  Makefile
  cmd/cli/Dockerfile
  cmd/cli/README.md
Labels: area/ci, area/cli

#363 cli: Add `flux-operator wait` commands
  cmd/cli/README.md
  cmd/cli/client.go
  cmd/cli/create_secret_basicauth_test.go
  cmd/cli/create_secret_proxy_test.go
  cmd/cli/create_secret_registry_test.go
  cmd/cli/create_secret_sops_test.go
  cmd/cli/suite_test.go
  cmd/cli/wait.go
  cmd/cli/wait_inputprovider.go
  cmd/cli/wait_inputprovider_test.go
  cmd/cli/wait_instance.go
  cmd/cli/wait_instance_test.go
  cmd/cli/wait_resourceset.go
  cmd/cli/wait_resourceset_test.go
Labels: enhancement, area/cli

#368 reporter: Add `flux_operator_info` metric
  internal/controller/fluxreport_controller.go
  internal/reporter/metrics.go
Labels: area/observability

#366 controller: Fix instance health check on subsequent reconciliations
  internal/controller/common.go
  internal/controller/fluxinstance_controller.go
  internal/controller/fluxinstance_controller_test.go
  internal/controller/resourceset_controller.go
Labels: bug, area/lifecycle

#369 Set the default CPU limit to `2000m` for Flux Operator
  config/manager/deployment.yaml
  config/olm/bundle/manifests/flux-operator.clusterserviceversion.yaml
Labels: area/lifecycle

#370 controller: Improve resource ownership takeover
  go.mod
  go.sum
  internal/controller/common.go
  internal/controller/fluxinstance_controller.go
  internal/controller/resourceset_controller.go
Labels: area/lifecycle

#375 reporter: Improve metrics collector
  docs/api/v1/resourceset.md
  internal/reporter/metrics.go
  internal/reporter/metrics_test.go
  internal/reporter/reconcilers.go
Labels: area/observability

#376 ci: Consolidate release workflow
  .github/workflows/push-images.yml
  .github/workflows/push-ubi.yml
  .github/workflows/release.yml
  docs/dev/README.md
Labels: area/ci
