Repository controlplaneio-fluxcd/flux-operator, pull requests merged in 2025-03, with the labels that each got.

#202 Add caching for GitHub App tokens
  cmd/operator/main.go
  go.mod
  go.sum
  internal/controller/resourcesetinputprovider_controller.go
  internal/controller/resourcesetinputprovider_controller_test.go
  internal/controller/testdata/rsa-private-key.pem
  internal/gitprovider/github.go
  internal/reporter/metrics.go
Labels: area/resourceset

#206 Delete cache events for RSIP and use library token cache flags
  cmd/operator/main.go
  go.mod
  go.sum
  internal/controller/resourcesetinputprovider_controller.go
Labels: area/resourceset

#205 Fix REPORTING_INTERVAL env var reading for FluxReport
  api/v1/fluxreport_types.go
Labels: area/observability

#207 Upgrade fluxcd/pkg/auth to v0.8.0
  go.mod
  go.sum
  internal/controller/resourcesetinputprovider_controller_test.go
Labels: dependencies

#209 Allow setting the reporting interval via cmd flags
  api/v1/fluxreport_types.go
  cmd/operator/main.go
  docs/api/v1/fluxreport.md
  internal/controller/fluxreport_controller.go
  internal/controller/fluxreport_controller_test.go
Labels: area/observability

#221 Update `fluxcd/pkg/runtime` to v0.56.0
  go.mod
  go.sum
Labels: dependencies
